bufの設定してみた
traPtitech/Emoine_R-UI pull request #211
Opened 2023-07-25 04:14 UTC by mehm8128

close https://github.com/traPtitech/Emoine_R-UI/issues/207

2023-07-25 13:52 UTC, ras0q commented on .gitignore
> +/src/lib/apis/buf/**
generated/bufの方がよさそう
あとbufは生成をまとめるツールの名前なのでここにbuf使うのは違和感がある
https://buf.build/docs/configuration/v1/buf-gen-yaml/ に沿うならprotoかprotobufかな

2023-07-27 00:30 UTC, ras0q requested changes

2023-07-27 00:30 UTC, ras0q commented on package.json
> +    "buf": "buf generate ../Emoine_R-server/api/proto/"
githubから取ってくるならこうするらしい
https://buf.build/docs/reference/inputs
```suggestion
    "buf": "buf generate https://github.com/traPtitech/Emoine_R.git#subdir=api/proto"
```

2023-07-27 00:32 UTC, ras0q commented on package.json
> +    "buf": "buf generate ../Emoine_R-server/api/proto/"
```suggestion
    "gen-api": "buf generate ../Emoine_R-server/api/proto/"
```
に置き換えてもいい気がする

2023-07-27 01:55 UTC, mehm8128 commented on package.json
> +    "buf": "buf generate ../Emoine_R-server/api/proto/"
確かに全置き換えなのでそれでいいですね

2023-07-27 01:55 UTC, mehm8128 commented on package.json
> +    "buf": "buf generate ../Emoine_R-server/api/proto/"
:tasukatta:

2023-07-27 01:58 UTC, ras0q commented on .gitignore
> +/src/lib/apis/buf/**
というか個人的にはそんな大きくもないしignoreしなくてもいいと思ってる

2023-07-27 02:02 UTC, mehm8128 commented
これscripts以下とかもいらなくなるのか

2023-07-27 02:02 UTC, mehm8128 commented
間違えた

2023-07-27 02:03 UTC, mehm8128 commented
なんか色々消せそうだけど完全に移行できてからでいいか

2023-07-27 02:06 UTC, mehm8128 commented on package.json
> +    "buf": "buf generate ../Emoine_R-server/api/proto/"
actionsでgen-api叩いて型情報とか作ってtype checkとかしてるからまだ消せなかった

2023-07-27 02:10 UTC, mehm8128 commented
このPRでどこまでやろうかな

2023-07-27 02:12 UTC, ras0q commented
もうopenapiをいじるつもりはないのでそこら辺全部消してもいいかも

2023-07-27 02:16 UTC, mehm8128 commented
じゃあ全部消しちゃって置き換えます

2023-07-27 02:51 UTC, ras0q commented
ごめんもしかしたらoauthだけREST使うかもだからもう少し待って欲しいかも

2023-07-27 02:53 UTC, mehm8128 commented
:a-::haakusimasita:

2023-07-27 02:57 UTC, mehm8128 commented
と思ったけど多分fetchするんじゃなくてlocation.hrefを変えるだけだったので影響なさそうです

2023-07-27 03:29 UTC, ras0q commented
普通にエンドポイントの形式がぜんぜん違ってくると思う
/emoine_r.v1.AdminAPIService/GetTokens とか

2023-07-29 08:05 UTC, ras0q commented
多分もうbigintじゃなくなってるはず

2023-07-29 14:51 UTC, mehm8128 commented
created_atとかはTimeStamp型で外部の型定義を使ってるっぽくてそれだけbigint使わないといけなくなっちゃってますね:eyes_komatta:
TimeStamp型自体扱い方複雑になりそうなのでどうにかしたいです

2023-08-07 12:24 UTC, ras0q commented
Timestampこれ以上できなさそうですね、、
個人的にはdayjs使うために自動生成されたclassにextend生やしてるのもあまり綺麗じゃないと思うんですがTimestampからdayjsに変換する関数生やすくらいでどうにかなりませんかね:thinking:

2023-08-07 13:19 UTC, mehm8128 commented
確かにそれでよさそうなので修正したやつpushしたんですけど、propsとして渡すときに型がずれてるらしくてエラー出てます

2023-08-07 13:25 UTC, mehm8128 commented
配列で初期化してたのが問題らしく、直った

2023-08-07 13:31 UTC, ras0q requested changes
まだやらなくていいんですがブランチこのままでマージしてほしくないのでrequest changes出します

2023-08-07 13:31 UTC, ras0q commented on package.json
> +    "gen-api": "node ./scripts/gen-api.js && buf generate https://github.com/traPtitech/Emoine_R.git#branch=feat/protobuf,subdir=api/proto",
```suggestion
    "gen-api": "node ./scripts/gen-api.js && buf generate https://github.com/traPtitech/Emoine_R.git#subdir=api/proto",
```

2023-08-10 02:38 UTC, ras0q reviewed
書いたつもりだったけどpendingだった

2023-08-10 14:38 UTC, mehm8128 commented on src/pages/admin/CreateNewMeetingPage.vue
> +const adminClient = useConnectClient(AdminAPIService)
蟹

2023-08-10 16:12 UTC, ras0q reviewed
書きました
あともうバックエンドのPRマージしたのでブランチmainに変えてOKです

2023-08-10 16:12 UTC, ras0q commented on src/lib/random.ts
> +}
別にdayjsを無理やり使う必要はなくてこんな感じでいいと思います
日付は適当なのでいい感じに
```suggestion
export const randomDate = () => {
  const start = new Date(1970, 0)
  const end = new Date(2100, 0)
  return new Date(randomNum(start.getTime(), end.getTime()))
}
```

2023-08-16 08:11 UTC, ras0q reviewed
みました
かなり好みかも

2023-08-16 08:11 UTC, ras0q commented on src/components/UI/DateChip.vue
> +  if (props.startedTime.isAfter(dayjs().valueOf())) return 'isPlanned'
引数なしの`dayjs()`は`new Date()`のラッパーなので個人的には`Date`をそのまま使えばこのファイルのdayjsへの依存がなくなっていいのでは、と思いました
しかも`valueOf`でnumberにしてるので`dayjs()`の恩恵がほぼ無さそう
dayjs使いたいなら`dayjs()`だけでも動く気がします(試してないので動かなかったらごめんなさい)

2023-08-16 08:11 UTC, ras0q commented on buf.gen.yaml
> +    # like remote generation does.
ここら辺のコメントはまあyaml読めばわかるやろって感じはするのでなくても良さそう

2023-08-16 08:11 UTC, ras0q commented on src/components/UI/DateChip.vue
> +  if (props.startedTime.isAfter(dayjs().valueOf())) return 'isPlanned'
そもそもこのファイルでdayjsで便利になってるとこほぼ無さそう🙃

2023-08-16 08:39 UTC, mehm8128 commented on src/components/UI/DateChip.vue
> +  if (props.startedTime.isAfter(dayjs().valueOf())) return 'isPlanned'
直しました
ちなみに`dayjs()`だけだと単位が1000倍くらいずれてるっぽくて駄目でした

2023-08-16 08:40 UTC, mehm8128 commented
ログ追加しました
streamの部分はmock書いたら書きます

2023-08-16 12:15 UTC, ras0q approved these changes
良さそうです:fro:

2023-08-20 01:22 UTC, ras0q approved these changes

2023-08-20 05:47 UTC, Rozelin-dc approved these changes
良さそうです！

2023-08-20 06:14 UTC, merged